version : "3.8"
services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ecommerce-net
  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_SEEDS=postgres
    ports:
      - "7233:7233"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecommerce-net
  temporal-ui:
    image: temporalio/ui:2.26.2
    container_name: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - "8080:8080"
    depends_on:
      - temporal
    networks:
      - ecommerce-net

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports: ["8081:8081"]
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkusOrderDb
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      TEMPORAL_TARGET: temporal:7233
      QUARKUS_HTTP_PORT: "8081"
    depends_on:
      temporal: { condition: service_started }
      postgres: { condition: service_healthy }
    networks: [ecommerce-net]

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports: ["8082:8082"]
    environment:
      TEMPORAL_TARGET: temporal:7233
      QUARKUS_HTTP_PORT: "8082"
    depends_on:
      temporal: { condition: service_started }
    networks: [ecommerce-net]

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    ports: ["8083:8083"]
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkusInventoryDb
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      TEMPORAL_TARGET: temporal:7233
      QUARKUS_HTTP_PORT: "8083"
    depends_on:
      temporal: { condition: service_started }
      postgres: { condition: service_healthy }
    networks: [ecommerce-net]

  shipping-service:
    build:
      context: .
      dockerfile: shipping-service/Dockerfile
    ports: ["8084:8084"]
    environment:
      TEMPORAL_TARGET: temporal:7233
      QUARKUS_HTTP_PORT: "8084"
    depends_on:
      temporal: { condition: service_started }
    networks: [ecommerce-net]


networks:
  ecommerce-net:
    driver: bridge




